# Generated by Django 4.1.3 on 2022-12-21 00:34

# migracion inicial para trabajar con el modelo "autor"

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("rate", models.BigIntegerField()),
                ("descripcion", models.CharField(max_length=4000)),
            ],
        ),
    ]
