# Generated by Django 4.1.3 on 2022-12-24 00:11

# migracion inicial para trabajar con el modelo "comentario"
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bcrud", "0002_entrada"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Comentador", models.CharField(max_length=100)),
                ("Texto", models.CharField(max_length=500)),
                ("Like", models.BooleanField()),
            ],
        ),
    ]
