# Generated by Django 4.1.3 on 2022-12-24 01:23
# migracion inicial para trabajar con el modelo "categoria"

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bcrud", "0003_comentario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=500)),
                (
                    "fecha",
                    models.DateField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
            ],
        ),
    ]
